connectedin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'connectedin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
)

perfis/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from perfis import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^perfil/(?P<perfil_id>[0-9]+)$', views.exibir, name='exibir'),
    url(r'^perfil/(?P<perfil_id>[0-9]+)/convidar$', views.convidar, name='convidar'),
    url(r'^perfil/(?P<convite_id>[0-9]+)/aceitar$', views.aceitar, name='aceitar'),
    url(r'^perfil/(?P<convite_id>[0-9]+)/deletar$', views.deletar, name='deletar'),
)

usuarios/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from views import RegistrarUsuarioView

urlpatterns = patterns('',
    url(r'^registrar/$', RegistrarUsuarioView.as_view(), name='registrar'),
)

perfis/models.py
from django.db import models

# Create your models here.

class Perfil(models.Model):
  nome = models.CharField(max_length=255, null=False)
  email = models.CharField(max_length=255, null=False)
  telefone = models.CharField(max_length=15, null=False)
  nome_empresa = models.CharField(max_length=255, null=False)
  contatos = models.ManyToManyField('self')

  def convidar(self, perfil_convidado):
    Convite(solicitante=self, convidado=perfil_convidado).save()

class Convite(models.Model):
  solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
  convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

  def aceitar(self):
    self.convidado.contatos.add(self.solicitante)
    self.solicitante.contatos.add(self.convidado)
    self.delete()

  def deletar(self):
    self.delete()

usuarios/models.py
from django.db import models

# Create your models here.

perfis/views.py
from django.shortcuts import render, redirect
from perfis.models import Perfil, Convite

# Create your views here.

def index(request):
  return render(request, 'index.html', {
    'perfis': Perfil.objects.all(),
    'perfil_logado': get_perfil_logado(request),
  })

def exibir(request, perfil_id):
  perfil = Perfil.objects.get(id=perfil_id)
  perfil_logado = get_perfil_logado(request)
  ja_eh_contato = perfil in perfil_logado.contatos.all()
  eu_mesmo = perfil == perfil_logado

  return render(request, 'perfil.html', {
    'perfil': perfil,
    'ja_eh_contato': ja_eh_contato,
    'eu_mesmo': eu_mesmo,
  })

def convidar(request, perfil_id):
  perfil_a_convidar = Perfil.objects.get(id=perfil_id)
  perfil_logado = get_perfil_logado(request)
  perfil_logado.convidar(perfil_a_convidar)
  return redirect('index')

def aceitar(request, convite_id):
  convite = Convite.objects.get(id=convite_id)
  convite.aceitar()
  return redirect('index')

def deletar(request, convite_id):
  convite = Convite.objects.get(id=convite_id)
  convite.deletar()
  return redirect('index')

def get_perfil_logado(request):
  return Perfil.objects.get(id=1)

usuarios/views.py
from django.shortcuts import render
from django.views.generic.base import View

# Create your views here.

class RegistrarUsuarioView(View):
  template_name = 'registrar.html'

  def get(self, request):
    return render(request, self.template_name)

  def post(self, request):
    return render(request, self.template_name)

perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'styles/main.css' %}" rel="stylesheet">
  <title>ConnectedIn</title>
</head>

<body>
  <div class="container">
    <div class="header">
      <div class="col-lg-12">
        <ul class="nav nav-pills pull-right">
          <li class="">
            <a href="{% url 'index' %}">Nome</a>
          </li>
          <li class="">
            <a href="/logout/">Logout</a>
          </li>
        </ul>
        <h3 class="text-muted">ConnectedIn</h3>
      </div>
    </div>

    <div class="row content">
      {% block body %} {% endblock %}
    </div>
  </div>
</body>

</html>

perfis/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">

  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Todos os Perfis</strong>
    </div>

    {% if perfis %}
    <ul>
      {% for perfil in perfis %}
      <li>
        <a href="{% url 'exibir' perfil.id%}">{{ perfil.nome }}</a> / {{ perfil.email }}
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>Nenhum Perfil encontrado</p>
    {% endif %}

    <div class="panel-default">
      {% with total_de_convites=perfil_logado.convites_recebidos.count %}
        {% if total_de_convites %}
        <div class='panel-heading'>
          <p>
            <strong>Você tem {{ total_de_convites }} convite{{ total_de_convites |pluralize }} aguardando aprovação</strong>
          </p>
          <ul>
            {% for convite in perfil_logado.convites_recebidos.all %}
            <li class='list-group-item'>
              {{ convite.solicitante.nome }}
              <div class='pull-right'>
                <a href='{% url "aceitar" convite.id %}'>aceitar</a>
                &nbsp;
                <a href='{% url "deletar" convite.id %}'>deletar</a>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% else %}
        <div class='panel-body'>
          <p>Nenhum convite recebido</p>
        </div>
        {% endif %}
      {% endwith %}
    </div>

    <div class="panel-default">
      {% with total_de_contatos=perfil_logado.contatos.count %}
        {% if total_de_contatos %}
        <div class='panel-heading'>
          <p>
            <strong>Você tem {{ total_de_contatos }} contatos{{ total_de_contatos |pluralize }}</strong>
          </p>
          <ul>
            {% for contato in perfil_logado.contatos.all %}
            <li class='list-group-item'>
              <a href='{% url "exibir" contato.id %}'>
                {{ contato.solicitante.nome }}
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% else %}
        <div class='panel-body'>
          <p>Você não possui contatos</p>
        </div>
        {% endif %}
      {% endwith %}
    </div>
    
  </div>
</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
<div class="row">
  <div class="col-lg-12">
    <h2 style="margin-top:0">{{perfil.nome}}</h2>
    <address>
      <strong>{{perfil.nome_empresa}}</strong>
      <br>
      <abbr title="Telefone">Tel:</abbr> {{perfil.telefone}}
      <br>
      <a href="mailto:{{perfil.email}}">{{perfil.email}}</a>
    </address>
    {% if not ja_eh_contato and not eu_mesmo%}
    <a href="{% url 'convidar' perfil.id %}">convidar</a>
    {% endif %}
  </div>
</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'styles/main.css' %}" rel="stylesheet">
  <title>ConnectedIn</title>
</head>

<body>
  <div class="container">
    <div class="row content">
      {% block body %} {% endblock %}
    </div>
  </div>
</body>

</html>

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
<form class='form-signin' action="{% url 'registrar' %}" method="POST">
  {% csrf_token %}
  <h2 class="form-signin-heading">Crie seu usuário</h2>

  <input id='id_email' name='email' type="email" class='form-control' placeholder='Email' required>
  <input id='id_nome' name='nome' type="text" class='form-control' placeholder='Nome' required>
  <input id='id_senha' name='senha' type="password" class='form-control' placeholder='Senha' required>
  <input id='id_telefone' name='telefone' type="tel" class='form-control' placeholder='Telefone'>
  <input id='id_nome_empresa' name='nome_empresa' type="text" class='form-control' placeholder='Empresa'>

  <hr/>

  <button class='btn btn-success btn-lg btn-block' type='submit'>Registrar</button>

</form>
{% endblock%}